//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;

public class Player : MonoBehaviour {

	public static Player instance {
		get;
		private set;
	}

	public GameObject LampLight;

	[HideInInspector]
	public Pickable inhand = null;
	
	public Pickable BOX;


	[HideInInspector]
	public Pickable inhand2 = null;
	
	public Pickable LAMP;

	protected Player (){

	}
	


	void Start(){

		Player.instance = this;

		Cursor.lockState = CursorLockMode.Locked;
		Cursor.visible = false;

		Application.LoadLevelAdditive("UIScene");

		if (BOX.worldObject.activeSelf) {
			BOX.handsObject.SetActive(false);
		}

		if (LAMP.worldObject.activeSelf) {
			LAMP.handsObject.SetActive(false);
		}
	}

	void Update(){
		if (LAMP.worldObject.activeSelf) {
			LampLight.SetActive (false);
		} else {
			LampLight.SetActive(true);
		}
	}
}


