//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Player : MonoBehaviour {

	public static Player instance {
		get;
		private set;
	}


	[HideInInspector]
	public Pickable inhand = null;
	
	public Pickable BOX;


	protected Player (){

	}
	


	void Start(){

		Player.instance = this;

		Cursor.lockState = CursorLockMode.Locked;
		Cursor.visible = false;

		if (BOX.worldObject.activeSelf) {
			BOX.handsObject.SetActive(false);
		}
	}
}


